-- SmartBiS_EngineData.lua — AUTO-GENERATED. Affix/style/proficiency/set-bonus tables.
SmartBiS_Affix = {
["str_of_strength"]={strength=7},
["str_of_agility"]={agility=8},
["str_of_stamina"]={stamina=9},
["str_of_the_tiger"]={strength=5,agility=5},
["str_of_the_monkey"]={agility=5,stamina=4},
["str_of_the_bear"]={strength=5,stamina=5},
["str_of_the_falcon"]={agility=5,intellect=5},
["str_of_champions_mind"]={strength=5,intellect=5},
["str_of_champions_spirit"]={strength=5,spirit=6},
["str_of_the_beast"]={agility=5,attackPower=6},
["str_of_the_champion"]={strength=5,attackPower=6},
["str_of_critical_might"]={strength=5,critRating=4},
["str_of_sharp_strikes"]={agility=5,critRating=4},
["str_of_rending_crit"]={attackPower=6,critRating=4},
["str_of_the_unyielding"]={stamina=6,critRating=4},
["str_of_expert_power"]={attackPower=6,hitRating=4},
["str_of_precise_might"]={strength=5,hitRating=4},
["str_of_accurate_strikes"]={agility=5,hitRating=4},
["str_of_steadfast"]={stamina=6,hitRating=4},
["str_of_swift_might"]={strength=5,hasteRating=4},
["str_of_the_deathblow"]={attackPower=6,hasteRating=4},
["str_of_swift_strikes"]={agility=5,hasteRating=4},
["str_of_quick_defense"]={stamina=6,hasteRating=4},
["str_of_swift_power"]={attackPower=6,expertise=4},
["str_of_expert_might"]={strength=5,expertise=4},
["str_of_expert_strikes_str"]={strength=5,expertise=4},
["str_of_expert_strikes_agi"]={agility=5,expertise=4},
["str_of_rending_str"]={strength=5,armorPenetration=4},
["str_of_rending_agi"]={agility=5,armorPenetration=4},
["str_of_the_ravager"]={attackPower=6,armorPenetration=4},
["str_of_dodging"]={stamina=6,dodge=6},
["str_of_parrying"]={stamina=6,parry=6},
["str_of_blocking"]={stamina=6,block=8},
["str_of_protection"]={stamina=6,blockValue=8},
["str_of_defense"]={stamina=6,defense=7},
["agi_of_strength"]={strength=7},
["agi_of_agility"]={agility=8},
["agi_of_stamina"]={stamina=9},
["agi_of_the_tiger"]={strength=5,agility=5},
["agi_of_the_monkey"]={agility=5,stamina=4},
["agi_of_the_bear"]={strength=5,stamina=5},
["agi_of_the_falcon"]={agility=5,intellect=5},
["agi_of_champions_mind"]={strength=5,intellect=5},
["agi_of_champions_spirit"]={strength=5,spirit=6},
["agi_of_the_beast"]={agility=5,attackPower=6},
["agi_of_the_champion"]={strength=5,attackPower=6},
["agi_of_critical_might"]={strength=5,critRating=4},
["agi_of_sharp_strikes"]={agility=5,critRating=4},
["agi_of_rending_crit"]={attackPower=6,critRating=4},
["agi_of_the_unyielding"]={stamina=6,critRating=4},
["agi_of_expert_power"]={attackPower=6,hitRating=4},
["agi_of_precise_might"]={strength=5,hitRating=4},
["agi_of_accurate_strikes"]={agility=5,hitRating=4},
["agi_of_steadfast"]={stamina=6,hitRating=4},
["agi_of_swift_might"]={strength=5,hasteRating=4},
["agi_of_the_deathblow"]={attackPower=6,hasteRating=4},
["agi_of_swift_strikes"]={agility=5,hasteRating=4},
["agi_of_quick_defense"]={stamina=6,hasteRating=4},
["agi_of_swift_power"]={attackPower=6,expertise=4},
["agi_of_expert_might"]={strength=5,expertise=4},
["agi_of_expert_strikes_str"]={strength=5,expertise=4},
["agi_of_expert_strikes_agi"]={agility=5,expertise=4},
["agi_of_rending_str"]={strength=5,armorPenetration=4},
["agi_of_rending_agi"]={agility=5,armorPenetration=4},
["agi_of_the_ravager"]={attackPower=6,armorPenetration=4},
["agi_of_dodging"]={stamina=6,dodge=6},
["agi_of_parrying"]={stamina=6,parry=6},
["agi_of_blocking"]={stamina=6,block=8},
["agi_of_protection"]={stamina=6,blockValue=8},
["agi_of_defense"]={stamina=6,defense=7},
["sta_of_strength"]={strength=7},
["sta_of_agility"]={agility=8},
["sta_of_stamina"]={stamina=9},
["sta_of_intellect"]={intellect=9},
["sta_of_spirit"]={spirit=10},
["sta_of_renewal"]={spirit=6},
["sta_of_spellpower"]={spellPower=10},
["sta_of_vital_regeneration"]={stamina=6},
["sta_of_the_tiger"]={strength=5,agility=5},
["sta_of_the_monkey"]={agility=5,stamina=4},
["sta_of_the_bear"]={strength=5,stamina=5},
["sta_of_the_falcon"]={agility=5,intellect=5},
["sta_of_the_eagle"]={intellect=6,stamina=5},
["sta_of_the_owl"]={intellect=6,spirit=6},
["sta_of_the_whale"]={spirit=6,stamina=5},
["sta_of_champions_mind"]={strength=5,intellect=5},
["sta_of_champions_spirit"]={strength=5,spirit=6},
["sta_of_the_beast"]={agility=5,attackPower=6},
["sta_of_the_champion"]={strength=5,attackPower=6},
["sta_of_prophecy"]={intellect=6,spellPower=6},
["sta_of_magical_fortitude"]={stamina=6,spellPower=6},
["sta_of_the_soulweaver"]={spirit=6,spellPower=6},
["sta_of_the_conjurer"]={intellect=6,spellDamage=7},
["sta_of_battle_magic"]={stamina=6,spellDamage=7},
["sta_of_the_spirit"]={spirit=6,spellDamage=7},
["sta_of_the_physician"]={intellect=6,healingPower=7},
["sta_of_vital_healing"]={stamina=6,healingPower=7},
["sta_of_the_hearth"]={spirit=6,healingPower=7},
["sta_of_critical_might"]={strength=5,critRating=4},
["sta_of_sharp_strikes"]={agility=5,critRating=4},
["sta_of_rending_crit"]={attackPower=6,critRating=4},
["sta_of_the_unyielding"]={stamina=6,critRating=4},
["sta_of_arcane_dominance"]={spellPower=6,critRating=4},
["sta_of_the_magus"]={intellect=6,critRating=4},
["sta_of_the_soothsayer"]={spirit=6,critRating=4},
["sta_of_expert_power"]={attackPower=6,hitRating=4},
["sta_of_precise_might"]={strength=5,hitRating=4},
["sta_of_accurate_strikes"]={agility=5,hitRating=4},
["sta_of_steadfast"]={stamina=6,hitRating=4},
["sta_of_arcane_precision"]={spellPower=6,hitRating=4},
["sta_of_the_seer"]={intellect=6,hitRating=4},
["sta_of_the_diligent"]={spirit=6,hitRating=4},
["sta_of_swift_might"]={strength=5,hasteRating=4},
["sta_of_the_deathblow"]={attackPower=6,hasteRating=4},
["sta_of_swift_strikes"]={agility=5,hasteRating=4},
["sta_of_swift_spells"]={spellPower=6,hasteRating=4},
["sta_of_the_arcane"]={intellect=6,hasteRating=4},
["sta_of_quick_defense"]={stamina=6,hasteRating=4},
["sta_of_the_oracle"]={spirit=6,hasteRating=4},
["sta_of_swift_power"]={attackPower=6,expertise=4},
["sta_of_expert_strikes_str"]={strength=5,expertise=4},
["sta_of_expert_strikes_agi"]={agility=5,expertise=4},
["sta_of_rending_str"]={strength=5,armorPenetration=4},
["sta_of_rending_agi"]={agility=5,armorPenetration=4},
["sta_of_the_ravager"]={attackPower=6,armorPenetration=4},
["sta_of_the_piercing_mind"]={intellect=6,spellPenetration=6},
["sta_of_vital_force"]={stamina=6,spellPenetration=6},
["sta_of_spirit_breaking"]={spirit=6,spellPenetration=6},
["sta_of_restoration"]={intellect=6,mp5=3},
["sta_of_vital_recovery"]={stamina=6,mp5=3},
["sta_of_soul_mending"]={spirit=6,mp5=3},
["sta_of_natures_grace"]={spirit=5,stamina=4,healingPower=5},
["sta_of_dodging"]={stamina=6,dodge=6},
["sta_of_parrying"]={stamina=6,parry=6},
["sta_of_blocking"]={stamina=6,block=8},
["sta_of_protection"]={stamina=6,blockValue=8},
["sta_of_defense"]={stamina=6,defense=7},
["int_of_spellpower"]={spellPower=10},
["int_of_intellect"]={intellect=9},
["int_of_stamina"]={stamina=9},
["int_of_vital_regeneration"]={stamina=6},
["int_of_spirit"]={spirit=10},
["int_of_renewal"]={spirit=6},
["int_of_the_eagle"]={intellect=6,stamina=5},
["int_of_the_owl"]={intellect=6,spirit=6},
["int_of_the_whale"]={spirit=6,stamina=5},
["int_of_prophecy"]={intellect=6,spellPower=6},
["int_of_magical_fortitude"]={stamina=6,spellPower=6},
["int_of_the_soulweaver"]={spirit=6,spellPower=6},
["int_of_the_conjurer"]={intellect=6,spellDamage=7},
["int_of_battle_magic"]={stamina=6,spellDamage=7},
["int_of_the_spirit"]={spirit=6,spellDamage=7},
["int_of_the_physician"]={intellect=6,healingPower=7},
["int_of_vital_healing"]={stamina=6,healingPower=7},
["int_of_the_hearth"]={spirit=6,healingPower=7},
["int_of_arcane_dominance"]={spellPower=6,critRating=4},
["int_of_the_magus"]={intellect=6,critRating=4},
["int_of_the_unyielding"]={stamina=6,critRating=4},
["int_of_the_soothsayer"]={spirit=6,critRating=4},
["int_of_arcane_precision"]={spellPower=6,hitRating=4},
["int_of_the_seer"]={intellect=6,hitRating=4},
["int_of_the_steadfast"]={stamina=6,hitRating=4},
["int_of_the_diligent"]={spirit=6,hitRating=4},
["int_of_swift_spells"]={spellPower=6,hasteRating=4},
["int_of_the_arcane"]={intellect=6,hasteRating=4},
["int_of_quick_defense"]={stamina=6,hasteRating=4},
["int_of_the_oracle"]={spirit=6,hasteRating=4},
["int_of_the_piercing_mind"]={intellect=6,spellPenetration=6},
["int_of_vital_force"]={stamina=6,spellPenetration=6},
["int_of_spirit_breaking"]={spirit=6,spellPenetration=6},
["int_of_restoration"]={intellect=6,mp5=3},
["int_of_vital_recovery"]={stamina=6,mp5=3},
["int_of_soul_mending"]={spirit=6,mp5=3},
["int_of_natures_grace"]={spirit=5,stamina=4,healingPower=5},
["spi_of_spellpower"]={spellPower=10},
["spi_of_intellect"]={intellect=9},
["spi_of_stamina"]={stamina=9},
["spi_of_vital_regeneration"]={stamina=6},
["spi_of_spirit"]={spirit=10},
["spi_of_renewal"]={spirit=6},
["spi_of_the_eagle"]={intellect=6,stamina=5},
["spi_of_the_owl"]={intellect=6,spirit=6},
["spi_of_the_whale"]={spirit=6,stamina=5},
["spi_of_prophecy"]={intellect=6,spellPower=6},
["spi_of_magical_fortitude"]={stamina=6,spellPower=6},
["spi_of_the_soulweaver"]={spirit=6,spellPower=6},
["spi_of_the_conjurer"]={intellect=6,spellDamage=7},
["spi_of_battle_magic"]={stamina=6,spellDamage=7},
["spi_of_the_spirit"]={spirit=6,spellDamage=7},
["spi_of_the_physician"]={intellect=6,healingPower=7},
["spi_of_vital_healing"]={stamina=6,healingPower=7},
["spi_of_the_hearth"]={spirit=6,healingPower=7},
["spi_of_arcane_dominance"]={spellPower=6,critRating=4},
["spi_of_the_magus"]={intellect=6,critRating=4},
["spi_of_the_unyielding"]={stamina=6,critRating=4},
["spi_of_the_soothsayer"]={spirit=6,critRating=4},
["spi_of_arcane_precision"]={spellPower=6,hitRating=4},
["spi_of_the_seer"]={intellect=6,hitRating=4},
["spi_of_the_steadfast"]={stamina=6,hitRating=4},
["spi_of_the_diligent"]={spirit=6,hitRating=4},
["spi_of_swift_spells"]={spellPower=6,hasteRating=4},
["spi_of_the_arcane"]={intellect=6,hasteRating=4},
["spi_of_quick_defense"]={stamina=6,hasteRating=4},
["spi_of_the_oracle"]={spirit=6,hasteRating=4},
["spi_of_the_piercing_mind"]={intellect=6,spellPenetration=6},
["spi_of_vital_force"]={stamina=6,spellPenetration=6},
["spi_of_spirit_breaking"]={spirit=6,spellPenetration=6},
["spi_of_restoration"]={intellect=6,mp5=3},
["spi_of_vital_recovery"]={stamina=6,mp5=3},
["spi_of_soul_mending"]={spirit=6,mp5=3},
["spi_of_natures_grace"]={spirit=5,stamina=4,healingPower=5},
}
SmartBiS_Styles = {
["Barbarian|Brutality"]={mh="1H",oh="1H"},
["Barbarian|Headhunting"]={mh="2H",oh="2H"},
["Barbarian|Ancestry"]={mh="1H",oh="1H"},
["Witch Doctor|Shadowhunting"]={mh="2H",oh="2H"},
["Witch Doctor|Voodoo"]={mh="2H",oh="2H"},
["Witch Doctor|Brewing"]={mh="2H",oh="2H"},
["Felsworn|Slayer"]={mh="1H",oh="1H"},
["Felsworn|Infernal"]={mh="2H",oh="2H"},
["Felsworn|Tyrant"]={mh="2H",oh="2H"},
["Witch Hunter|Boltslinger"]={mh="1H",oh="1H"},
["Witch Hunter|Houndmaster"]={mh="1H",oh="1H"},
["Witch Hunter|Inquisition"]={mh="1H",oh="1H"},
["Witch Hunter|Black Knight"]={mh="2H",oh="2H"},
["Stormbringer|Maelstrom"]={mh="2H",oh="2H"},
["Stormbringer|Lightning"]={mh="2H",oh="2H"},
["Stormbringer|Wind"]={mh="2H",oh="2H"},
["Knight of Xoroth|Hellfire"]={mh="2H",oh="2H"},
["Knight of Xoroth|Defiance"]={mh="1H",oh="shield"},
["Knight of Xoroth|War"]={mh="2H",oh="2H"},
["Guardian|Gladiator"]={mh="2H",oh="2H"},
["Guardian|Inspiration"]={mh="1H",oh="shield"},
["Guardian|Vanguard"]={mh="1H",oh="shield"},
["Templar|Oathkeeper"]={mh="2H",oh="2H"},
["Templar|Zealot"]={mh="1H",oh="1H"},
["Templar|Crusader"]={mh="2H",oh="2H"},
["Bloodmage|Fleshweaver"]={mh="2H",oh="2H"},
["Bloodmage|Sanguine"]={mh="2H",oh="2H"},
["Bloodmage|Accursed"]={mh="2H",oh="2H"},
["Bloodmage|Eternal"]={mh="1H",oh="1H"},
["Ranger|Archery"]={mh="2H",oh="2H"},
["Ranger|Brigand"]={mh="1H",oh="1H"},
["Ranger|Farstrider"]={mh="2H",oh="2H"},
["Chronomancer|Infinite"]={mh="2H",oh="2H"},
["Chronomancer|Time"]={mh="2H",oh="2H"},
["Chronomancer|Artificer"]={mh="2H",oh="2H"},
["Necromancer|Animation"]={mh="2H",oh="2H"},
["Necromancer|Death"]={mh="2H",oh="2H"},
["Necromancer|Rime"]={mh="2H",oh="2H"},
["Pyromancer|Incineration"]={mh="2H",oh="2H"},
["Pyromancer|Flameweaving"]={mh="2H",oh="2H"},
["Pyromancer|Draconic"]={mh="2H",oh="2H"},
["Cultist|Heretic"]={mh="2H",oh="2H"},
["Cultist|Corruption"]={mh="1H",oh="shield"},
["Cultist|Godblade"]={mh="2H",oh="2H"},
["Cultist|Dreadnought"]={mh="1H",oh="shield"},
["Starcaller|Sentinel"]={mh="2H",oh="2H"},
["Starcaller|Warden"]={mh="1H",oh="1H"},
["Starcaller|Moon Priest"]={mh="2H",oh="2H"},
["Starcaller|Moon Guard"]={mh="1H",oh="shield"},
["Sun Cleric|Piety"]={mh="1H",oh="shield"},
["Sun Cleric|Blessings"]={mh="1H",oh="shield"},
["Sun Cleric|Valkyrie"]={mh="2H",oh="2H"},
["Sun Cleric|Seraphim"]={mh="1H",oh="shield"},
["Tinker|Mechanics"]={mh="2H",oh="2H"},
["Tinker|Invention"]={mh="2H",oh="2H"},
["Tinker|Demolition"]={mh="2H",oh="2H"},
["Primalist|Grovekeeper"]={mh="2H",oh="2H"},
["Primalist|Wildwalker"]={mh="1H",oh="1H"},
["Primalist|Mountain King"]={mh="1H",oh="1H"},
["Primalist|Geomancy"]={mh="1H",oh="offhand"},
["Reaper|Soul"]={mh="1H",oh="1H"},
["Reaper|Harvest"]={mh="2H",oh="2H"},
["Reaper|Domination"]={mh="2H",oh="2H"},
["Venomancer|Fortitude"]={mh="1H",oh="1H"},
["Venomancer|Stalking"]={mh="2H",oh="2H"},
["Venomancer|Rotweaver"]={mh="2H",oh="2H"},
["Venomancer|Vizier"]={mh="2H",oh="2H"},
["Runemaster|Engravement"]={mh="1H",oh="1H"},
["Runemaster|Glyphic"]={mh="2H",oh="2H"},
["Runemaster|Riftblade"]={mh="1H",oh="1H"},
}
SmartBiS_Prof = {
["Barbarian|Brutality"]={"Daggers"},
["Barbarian|Headhunting"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Barbarian|Ancestry"]={"Daggers"},
["Witch Doctor|Shadowhunting"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Witch Doctor|Voodoo"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Witch Doctor|Brewing"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Felsworn|Slayer"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Felsworn|Infernal"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Felsworn|Tyrant"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Witch Hunter|Boltslinger"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Witch Hunter|Houndmaster"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Witch Hunter|Inquisition"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Witch Hunter|Black Knight"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Stormbringer|Maelstrom"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Stormbringer|Lightning"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Stormbringer|Wind"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Knight of Xoroth|Hellfire"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Knight of Xoroth|Defiance"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Knight of Xoroth|War"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Guardian|Gladiator"]={"Polearms"},
["Guardian|Inspiration"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Guardian|Vanguard"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Templar|Oathkeeper"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Templar|Zealot"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Templar|Crusader"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Bloodmage|Fleshweaver"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Bloodmage|Sanguine"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Bloodmage|Accursed"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Bloodmage|Eternal"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Ranger|Archery"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Ranger|Brigand"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Ranger|Farstrider"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Chronomancer|Infinite"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Chronomancer|Time"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Chronomancer|Artificer"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Necromancer|Animation"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Necromancer|Death"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Necromancer|Rime"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Pyromancer|Incineration"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Pyromancer|Flameweaving"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Pyromancer|Draconic"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Cultist|Heretic"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Cultist|Corruption"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Cultist|Godblade"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Cultist|Dreadnought"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Starcaller|Sentinel"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Starcaller|Warden"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Starcaller|Moon Priest"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Starcaller|Moon Guard"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Sun Cleric|Piety"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Sun Cleric|Blessings"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Sun Cleric|Valkyrie"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Sun Cleric|Seraphim"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Tinker|Mechanics"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Tinker|Invention"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Tinker|Demolition"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Primalist|Grovekeeper"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Primalist|Wildwalker"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Primalist|Mountain King"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Primalist|Geomancy"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Reaper|Soul"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Reaper|Harvest"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Reaper|Domination"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Venomancer|Fortitude"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Venomancer|Stalking"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Venomancer|Rotweaver"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Venomancer|Vizier"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Runemaster|Engravement"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
["Runemaster|Glyphic"]={"Swords","Polearms","Axes","Maces","Staves","Two-Handed Maces","Two-Handed Axes"},
["Runemaster|Riftblade"]={"Maces","Swords","Axes","Daggers","Fist Weapons","One-Handed Swords","One-Handed Maces"},
}
SmartBiS_SetBonus = {
["t2:Bloodfang Armor"]={thr={3,6},[3]=true,[6]=true},
["t2:Stormrage Predator"]={thr={3,6},[3]=true,[6]=true},
["t2:Stormrage's Ferocity"]={thr={3,6},[3]={critRating=30},[6]=true},
["t2.5:Deathdealer's Embrace"]={thr={2,4},[2]=true,[4]={attackPower=10}},
["t2.5:Genesis Battlewraps"]={thr={2,4},[2]=true,[4]=true},
["t3:Dreamwalker Battlewraps"]={thr={2,4,6,8},[2]=true,[4]=true,[6]=true,[8]=true},
["t3:Bonescythe Armor"]={thr={2,4,6,8},[2]=true,[4]=true,[6]={dodge=42},[8]=true},
["zg:Madcap's Outfit"]={thr={3,5},[3]=true,[5]=true},
["t2.5:Emblems of Veiled Shadows"]={thr={2,4},[2]=true,[4]=true},
["t1:Cenarion Predator"]={thr={3,6},[3]={hitRating=20},[6]=true},
["t3:Dreamwalker Harness"]={thr={2,4,6,8},[2]=true,[4]=true,[6]={armor=3},[8]=true},
["t1:Nightslayer Armor"]={thr={3,6},[3]=true,[6]=true},
["t1:Cenarion Guardian"]={thr={3,6},[3]=true,[6]=true},
["t2.5:Genesis Harness"]={thr={2,4},[2]={attackPower=10},[4]={dodge=140}},
["zg:Predator's Armor"]={thr={3,5},[3]=true,[5]={attackPower=45}},
["t2:Dragonstalker Armor"]={thr={3,6},[3]=true,[6]=true},
["t2.5:Striker's Garb"]={thr={2,4},[2]={attackPower=45},[4]=true},
["t3:Cryptstalker Armor"]={thr={2,4,6,8},[2]=true,[4]={attackPower=60},[6]=true,[8]=true},
["t1:Giantstalker Armor"]={thr={3,6},[3]={agility=10},[6]=true},
["t2:Fury of the Ten Storms"]={thr={3,6},[3]=true,[6]=true},
["t3:Frozen Vrykul's Battlegarb"]={thr={2,4,6,8},[2]=true,[4]=true,[6]=true,[8]=true},
["t2:Dragonscale Battlegear"]={thr={3,6},[3]=true,[6]=true},
["t2:Stormrage Raiment"]={thr={3,6},[3]={spirit=35},[6]={hasteRating=50}},
["t3:Frostfire Regalia"]={thr={2,4,6,8},[2]=true,[4]=true,[6]=true,[8]=true},
["t2.5:Stormcaller's Regalia"]={thr={2,4},[2]=true,[4]=true},
["t1:Regalia of Prophecy"]={thr={3,6},[3]=true,[6]={critRating=7,hasteRating=5}},
["t2:Regalia of Transcendence"]={thr={3,6},[3]={hasteRating=15},[6]={critRating=60}},
["t3:Vestments of Faith"]={thr={2,4,6,8},[2]=true,[4]=true,[6]=true,[8]=true},
["zg:Haruspex's Garb"]={thr={3,5},[3]={spirit=20},[5]=true},
["t1:Cenarion Regalia"]={thr={3,6},[3]=true,[6]={spirit=10}},
["t1:Arcanist Regalia"]={thr={3,6},[3]={spellPower=18},[6]=true},
["t2:Stormrage Vestments"]={thr={3,6},[3]={spirit=35},[6]=true},
["t2:Vestments of Transcendence"]={thr={3,6},[3]=true,[6]=true},
["t3:Dreamwalker Garb"]={thr={2,4,6,8},[2]={spellPower=30},[4]=true,[6]=true,[8]=true},
["t3:Dreamwalker Raiment"]={thr={2,4,6,8},[2]=true,[4]=true,[6]=true,[8]={hasteRating=100}},
["t2:Netherwind Regalia"]={thr={3,6},[3]={critRating=30},[6]=true},
["t1:Vestments of Prophecy"]={thr={3,6},[3]=true,[6]=true},
["t3:Regalia of Faith"]={thr={2,4,6,8},[2]=true,[4]=true,[6]={armor=550,arcaneResist=30,fireResist=30,frostResist=30,natureResist=30,shadowResist=30},[8]=true},
["zg:Augur's Regalia"]={thr={3,5},[3]=true,[5]={spellPower=20}},
["t2:The Ten Storms"]={thr={3,6},[3]={hasteRating=20},[6]=true},
["t2:Regalia of Ten Storms"]={thr={3,6},[3]={critRating=28},[6]=true},
["t3:Earthshatter Raiment"]={thr={2,4,6,8},[2]={critRating=70},[4]={hasteRating=30},[6]=true,[8]=true},
["zg:Illusionist's Attire"]={thr={3,5},[3]=true,[5]=true},
["t3:Earthshatter Regalia"]={thr={2,4,6,8},[2]=true,[4]=true,[6]=true,[8]=true},
["t2.5:Stormcaller's Battlegear"]={thr={2,4},[2]=true,[4]=true},
["t1:Earthfury Harness"]={thr={3,6},[3]=true,[6]=true},
["t3:The Earthshatterer"]={thr={2,4,6,8},[2]=true,[4]=true,[6]=true,[8]={spellPower=6,agility=60}},
["t1:Charred Defender's Armor"]={thr={3,6},[3]={armor=400},[6]={armor=3}},
["t1:Felheart Raiment"]={thr={3,6},[3]={hasteRating=10},[6]=true},
["t2.5:Doomcaller's Attire"]={thr={2,4},[2]={spellPower=35},[4]=true},
["t2:Nemesis Raiment"]={thr={3,6},[3]={spellPower=23},[6]={hasteRating=60}},
["t3:Plagueheart Raiment"]={thr={2,4,6,8},[2]=true,[4]={spellPower=40},[6]=true,[8]={hasteRating=80}},
["t2.5:Enigma Vestments"]={thr={2,4},[2]={critRating=42},[4]=true},
["zg:Demoniac's Threads"]={thr={3,5},[3]=true,[5]=true},
["t2:Judgement Armor"]={thr={3,6},[3]={attackPower=38,spellPower=26},[6]=true},
["t1:Lawbringer Battlegear"]={thr={3,6},[3]=true,[6]=true},
["t2:Fury of Wrath"]={thr={3,6},[3]={critRating=28,attackPower=40},[6]=true},
["t2.5:Avenger's Battlegear"]={thr={2,4},[2]=true,[4]=true},
["t3:Redemption Battleplate"]={thr={2,4,6,8},[2]=true,[4]=true,[6]=true,[8]=true},
["zg:Freethinker's Armor"]={thr={3,5},[3]={attackPower=25,armor=250},[5]=true},
["t3:Dreadborne Armor"]={thr={2,4,6,8},[2]=true,[4]=true,[6]={armor=2000},[8]={hasteRating=8,armorPenetration=4}},
["t3:Dreadnaught's Battlegear"]={thr={2,4,6,8},[2]=true,[4]={hitRating=16,stamina=35},[6]={stamina=8,armor=100},[8]=true},
["t3:Redemption Armor"]={thr={2,4,6,8},[2]=true,[4]=true,[6]=true,[8]=true},
["t1:Battlegear of Might"]={thr={3,6},[3]=true,[6]=true},
["t2.5:Conqueror's Arsenal"]={thr={2,4},[2]={dodge=16,parry=16},[4]=true},
["t3:Dreadnaught's Plate"]={thr={2,4,6,8},[2]=true,[4]={hitRating=16,stamina=35},[6]=true,[8]=true},
["t3:Redemption Regalia"]={thr={2,4,6,8},[2]=true,[4]={spellCritRating=42,critRating=42},[6]=true,[8]=true},
["t2.5:Avenger's Armor"]={thr={2,4},[2]={block=25},[4]={spellPower=75}},
["t2.5:Conqueror's Battlegear"]={thr={2,4},[2]={critRating=28},[4]=true},
["t2:Arsenal of Wrath"]={thr={3,6},[3]=true,[6]=true},
["t2:Battlegear of Wrath"]={thr={3,6},[3]={attackPower=2},[6]=true},
["t2:Judgement Guard"]={thr={3,6},[3]=true,[6]={block=25}},
["t2.5:Conqueror's Plate"]={thr={2,4},[2]={block=25},[4]=true},
["zg:Vindicator's Battlegear"]={thr={3,5},[3]=true,[5]=true},
["t1:Lawbringer Armor"]={thr={3,6},[3]={stamina=25},[6]=true},
["t1:Fury of Might"]={thr={3,6},[3]={critRating=21},[6]=true},
["t1:Armor of Might"]={thr={3,6},[3]=true,[6]=true},
["t2.5:Vestments of the Oracle"]={thr={2,4},[2]={critRating=14,hasteRating=10,spirit=20},[4]=true},
["t2:Judgement Rainment"]={thr={3,6},[3]={hasteRating=30},[6]={critRating=70}},
["t2.5:Avenger's Rainment"]={thr={2,4},[2]=true,[4]={hasteRating=10}},
["t2.5:Stormcaller's Garb"]={thr={2,4},[2]={hasteRating=30},[4]={critRating=14}},
["t1:The Earthfury"]={thr={3,6},[3]=true,[6]=true},
["t1:Lawbringer Raiment"]={thr={3,6},[3]=true,[6]={healingPower=50}},
["t1:Earthfury Regalia"]={thr={3,6},[3]=true,[6]={spellPower=40}},
}
